<?php

class EVOLT_eVoltMailchimpForm_Widget extends Wider_Theme_Core_Widget_Base{
    protected $name = 'evolt_mailchimp_form';
    protected $title = 'Wider Mailchimp Form';
    protected $icon = 'eicon-email-field';
    protected $categories = array( 'wider-theme-core' );
    protected $params = '{"sections":[{"name":"source_section","label":"Color Settings","tab":"style","controls":[{"name":"style","label":"Style","type":"select","options":{"style1":"Style 1","style2":"Style 2","style3":"Style 3"},"default":"style1"},{"name":"title","label":"Title","type":"text","label_block":true,"condition":{"style":["style2","style3"]}},{"name":"title_typography","label":"Title Typography","type":"typography","control_type":"group","selector":"{{WRAPPER}} .evolt-mailchimp1 .evolt-mailchimp-meta .wg-title","condition":{"style":["style2","style3"]}},{"name":"description_text","label":"Description","type":"textarea","placeholder":"Enter your description","rows":10,"show_label":false,"condition":{"style":["style3"]}},{"name":"box_image_left","label":"Box Image Left","type":"media","condition":{"style":["style2"]}},{"name":"box_image","label":"Box Background Image","type":"media","condition":{"style":["style2"]}},{"name":"box_bg_color","label":"Box Background Color","type":"color","selectors":{"{{WRAPPER}} .evolt-mailchimp1.style2":"background-color: {{VALUE}};"},"condition":{"style":["style2"]}},{"name":"input_color","label":"Input Color","type":"color","selectors":{"{{WRAPPER}} .evolt-mailchimp.evolt-mailchimp1 .mc4wp-form .mc4wp-form-fields input":"color: {{VALUE}};"}},{"name":"input_bg_color","label":"Input Background Color","type":"color","selectors":{"{{WRAPPER}} .evolt-mailchimp.evolt-mailchimp1 .mc4wp-form .mc4wp-form-fields input":"background-color: {{VALUE}};"}},{"name":"input_border_color","label":"Input Focus Border Color","type":"color","selectors":{"{{WRAPPER}} .evolt-mailchimp1.style1 .mc4wp-form .mc4wp-form-fields input[type=\"email\"], {{WRAPPER}} .evolt-mailchimp1.style1 .mc4wp-form .mc4wp-form-fields input[type=\"text\"]":"border-color: {{VALUE}};"}},{"name":"input_focus_border_color","label":"Input Focus Border Color","type":"color","selectors":{"{{WRAPPER}} .evolt-mailchimp1.style1 .mc4wp-form .mc4wp-form-fields input[type=\"email\"]:focus, {{WRAPPER}} .evolt-mailchimp1.style1 .mc4wp-form .mc4wp-form-fields input[type=\"text\"]:focus":"border-color: {{VALUE}};"}},{"name":"button_icon_color","label":"Button Icon Color","type":"color","selectors":{"{{WRAPPER}} .evolt-mailchimp1.style1 .mc4wp-form .mc4wp-form-fields::after":"color: {{VALUE}};"}},{"name":"button_bg_color","label":"Button Background Color","type":"color","selectors":{"{{WRAPPER}} .evolt-mailchimp.evolt-mailchimp1 .mc4wp-form .mc4wp-form-fields:before":"background: {{VALUE}};"}}]}]}';
    protected $styles = array(  );
    protected $scripts = array(  );
}