<?php

class EVOLT_EvoltTabs_Widget extends Wider_Theme_Core_Widget_Base{
    protected $name = 'evolt_tabs';
    protected $title = 'Wider Tabs';
    protected $icon = 'eicon-tabs';
    protected $categories = array( 'wider-theme-core' );
    protected $params = '{"sections":[{"name":"section_tabs","label":"Tabs","tab":"content","controls":[{"name":"active_tab","label":"Active Tab","type":"number","default":1,"separator":"after"},{"name":"tabs","label":"Tabs Items","type":"repeater","controls":[{"name":"evolt_icon","label":"Icon","type":"icons","fa4compatibility":"icon"},{"name":"tab_title","label":"Title","type":"text","default":"Tab Title","placeholder":"Tab Title","label_block":true},{"name":"content_type","label":"Content Type","type":"select","default":"text_editor","options":{"text_editor":"Text Editor","template":"Template"}},{"name":"tab_content","label":"Content","type":"wysiwyg","default":"Tab Content","placeholder":"Tab Content","show_label":false,"condition":{"content_type":"text_editor"}},{"name":"tab_content_template","label":"Template","type":"select","default":"","options":{"":"Select Template","7647":"New table today","7640":"Pricing Table","7635":"Pricing Table","7625":"table","7587":"Default Kit","7430":"Products Coffee - Top Rated","7427":"Products Coffee - Best Sellers","7424":"Products Coffee - New","6424":"Products - On Sale","6421":"Products - Top Rateted","6418":"Products - Featured","12":"Default Kit"},"condition":{"content_type":"template"}},{"name":"form_id","label":"Select Contact Form 7","type":"select","options":"","condition":{"content_type":"form"}}],"title_field":"{{{ tab_title }}}"},{"name":"tab_type","label":"Type","type":"select","options":{"horizontal":"Horizontal"},"default":"horizontal","condition":{"layout":"n"}},{"name":"tab_style","label":"Style","type":"select","options":{"style1":"Style 1","style2":"Style 2"},"default":"style1","condition":{"tab_type":"horizontal"}},{"name":"title_color","label":"Title Color","type":"color","selectors":{"{{WRAPPER}} .evolt-tabs .evolt-tabs-title .evolt-tab-title":"color: {{VALUE}};"}},{"name":"title_active_color","label":"Title Active Color","type":"color","selectors":{"{{WRAPPER}} .evolt-tabs .evolt-tabs-title .evolt-tab-title.active":"color: {{VALUE}};"}},{"name":"box_title_color","label":"Title Box Color","type":"color","selectors":{"{{WRAPPER}} .evolt-tabs .evolt-tabs-title .evolt-tab-title":"background-color: {{VALUE}};"},"condition":{"tab_style":"style1"}},{"name":"box_title_color_hover","label":"Title Box Color - Hover\/Active","type":"color","selectors":{"{{WRAPPER}} .evolt-tabs--horizontal1 .evolt-tabs-title .evolt-tab-title:hover, {{WRAPPER}} .evolt-tabs--horizontal1 .evolt-tabs-title .evolt-tab-title.active":"background-color: {{VALUE}};"},"condition":{"tab_style":"style1"}},{"name":"content_color","label":"Content Color","type":"color","selectors":{"{{WRAPPER}} .evolt-tabs .evolt-tabs-content .evolt-tab-content":"color: {{VALUE}};"}}]}]}';
    protected $styles = array(  );
    protected $scripts = array( 'evolt-tabs-widget-js' );
}